on:
    workflow_dispatch:
        inputs:
            tag_name:
                description: 'Tag name for the release'
                required: true
                default: 'v1.0.0'
            release_name:
                description: 'Release name'
                required: true
                default: 'v1.0.0'
            release_body:
                description: 'Release body'
                required: true
                default: 'Initial release'

name: Create Release
jobs:
    build:
        permissions: write-all
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - run: npm ci
            - run: npm run build
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
              with:
                  tag_name: ${{ github.event.inputs.tag_name }}
                  release_name: Release ${{ github.event.inputs.release_name }}
                  body: ${{ github.event.inputs.release_body }}
                  draft: false
                  prerelease: false
